blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'

urlpatterns = [
    url(r'^tag/(?P<tag>[-\w]+)/', views.tag_view, name="tag"),
    url(r'^category/(?P<category>[-\w]+)/feed/$', views.LatestCategoryFeed(), name="category_feed"),
    url(r'^category/(?P<category>[-\w]+)/', views.category_view, name="category"),
    url(r'^author/(?P<author>[-\w]+)/', views.author_view, name="author"),
    url(r'(?P<blog_slug>[\w-]+)/rss.*/',
        views.LatestEntriesFeed(),
        name="latest_entries_feed"),
    url(r'(?P<blog_slug>[\w-]+)/atom.*/',
        views.LatestEntriesFeedAtom(),
        name="latest_entries_feed_atom"),
]

ndmastories/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [
    url(r'^django-admin/', admin.site.urls),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),

    url(r'^blog/', include('blog.urls', namespace="blog")),

    url(r'', include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r"", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r"^pages/", include(wagtail_urls)),
]

blog/models.py
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db.models import Count
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import get_object_or_404
from django.template.defaultfilters import slugify
from wagtail.snippets.models import register_snippet
from taggit.models import Tag

from .abstract import (
    BlogCategoryAbstract,
    BlogCategoryBlogPageAbstract,
    BlogIndexPageAbstract,
    BlogPageAbstract,
    BlogPageTagAbstract
)


COMMENTS_APP = getattr(settings, 'COMMENTS_APP', None)


class BlogIndexPage(BlogIndexPageAbstract):
    class Meta:
        verbose_name = _('Blog index')

    @property
    def blogs(self):
        # Get list of blog pages that are descendants of this page
        blogs = BlogPage.objects.descendant_of(self).live()
        blogs = blogs.order_by(
            '-date'
        ).select_related('owner').prefetch_related(
            'tagged_items__tag',
            'categories',
            'categories__category',
        )
        return blogs

    def get_context(self, request, tag=None, category=None, author=None, *args,
                    **kwargs):
        context = super(BlogIndexPage, self).get_context(
            request, *args, **kwargs)
        blogs = self.blogs

        if tag is None:
            tag = request.GET.get('tag')
        if tag:
            blogs = blogs.filter(tags__slug=tag)
        if category is None:  # Not coming from category_view in views.py
            if request.GET.get('category'):
                category = get_object_or_404(
                    BlogCategory, slug=request.GET.get('category'))
        if category:
            if not request.GET.get('category'):
                category = get_object_or_404(BlogCategory, slug=category)
            blogs = blogs.filter(categories__category__name=category)
        if author:
            if isinstance(author, str) and not author.isdigit():
                blogs = blogs.filter(author__username=author)
            else:
                blogs = blogs.filter(author_id=author)

        # Pagination
        page = request.GET.get('page')
        page_size = 10
        if hasattr(settings, 'BLOG_PAGINATION_PER_PAGE'):
            page_size = settings.BLOG_PAGINATION_PER_PAGE

        paginator = None
        if page_size is not None:
            paginator = Paginator(blogs, page_size)  # Show 10 blogs per page
            try:
                blogs = paginator.page(page)
            except PageNotAnInteger:
                blogs = paginator.page(1)
            except EmptyPage:
                blogs = paginator.page(paginator.num_pages)

        context['blogs'] = blogs
        context['category'] = category
        context['tag'] = tag
        context['author'] = author
        context['COMMENTS_APP'] = COMMENTS_APP
        context['paginator'] = paginator
        context = get_blog_context(context)

        return context

    subpage_types = ['blog.BlogPage']


@register_snippet
class BlogCategory(BlogCategoryAbstract):
    class Meta:
        ordering = ['name']
        verbose_name = _("Blog Category")
        verbose_name_plural = _("Blog Categories")


class BlogCategoryBlogPage(BlogCategoryBlogPageAbstract):
    class Meta:
        pass


class BlogPageTag(BlogPageTagAbstract):
    class Meta:
        pass


@register_snippet
class BlogTag(Tag):
    class Meta:
        proxy = True


def get_blog_context(context):
    """ Get context data useful on all blog related pages """
    context['authors'] = get_user_model().objects.filter(
        owned_pages__live=True,
        owned_pages__content_type__model='blogpage'
    ).annotate(Count('owned_pages')).order_by('-owned_pages__count')
    context['all_categories'] = BlogCategory.objects.all()
    context['root_categories'] = BlogCategory.objects.filter(
        parent=None,
    ).prefetch_related(
        'children',
    ).annotate(
        blog_count=Count('blogpage'),
    )
    return context


class BlogPage(BlogPageAbstract):
    class Meta:
        verbose_name = _('Blog page')
        verbose_name_plural = _('Blog pages')

    def get_blog_index(self):
        # Find closest ancestor which is a blog index
        return self.get_ancestors().type(BlogIndexPage).last()

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request, *args, **kwargs)
        context['blogs'] = self.get_blog_index().blogindexpage.blogs
        context = get_blog_context(context)
        context['COMMENTS_APP'] = COMMENTS_APP
        return context

    parent_page_types = ['blog.BlogIndexPage']

blog/views.py
from django.contrib.syndication.views import Feed
from django.utils.feedgenerator import Atom1Feed
from .models import BlogIndexPage, BlogPage, BlogCategory
from django.shortcuts import get_object_or_404
from django.conf import settings


def tag_view(request, tag):
    index = BlogIndexPage.objects.first()
    return index.serve(request, tag=tag)


def category_view(request, category):
    index = BlogIndexPage.objects.first()
    return index.serve(request, category=category)


def author_view(request, author):
    index = BlogIndexPage.objects.first()
    return index.serve(request, author=author)


class LatestEntriesFeed(Feed):
    '''
    If a URL ends with "rss" try to find a matching BlogIndexPage
    and return its items.
    '''

    def get_object(self, request, blog_slug):
        return get_object_or_404(BlogIndexPage, slug=blog_slug)

    def title(self, blog):
        if blog.seo_title:
            return blog.seo_title
        return blog.title

    def link(self, blog):
        return blog.full_url

    def description(self, blog):
        return blog.search_description

    def items(self, blog):
        num = getattr(settings, 'BLOG_PAGINATION_PER_PAGE', 10)
        return blog.get_descendants().order_by('-first_published_at')[:num]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.specific.body

    def item_link(self, item):
        return item.full_url

    def item_pubdate(self, blog):
        return blog.first_published_at


class LatestEntriesFeedAtom(LatestEntriesFeed):
    feed_type = Atom1Feed


class LatestCategoryFeed(Feed):
    description = "A Blog"

    def title(self, category):
        return "Blog: " + category.name

    def link(self, category):
        return "/blog/category/" + category.slug

    def get_object(self, request, category):
        return get_object_or_404(BlogCategory, slug=category)

    def items(self, obj):
        return BlogPage.objects.filter(
            categories__category=obj).order_by('-date')[:5]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.body

ndmastories/templates/blog/blog_index_page.html
{% extends "base.html" %}
{% load wagtailcore_tags static wagtailimages_tags blogapp_tags el_pagination_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 title">
            {% if category %}
                <h2>{{ category }}</h2>
            {% endif %}
            {% if tag %}
                <h2>Posts tagged with '{{ tag }}'</h2>
            {% endif %}
            {% if not category and not tag %}
                <!-- <p>
                    &nbsp;
                </p> -->
            {% endif %}
            {% for rl in self.related_links.all %}
                <p>{{ rl.title }}: <a href='{{ rl.link_page.url }}'>{{ rl.link_page }}</a></p>
            {% endfor %}

        </div>
    </div>
    <div class="row">

    {% if blogs %}
        {% paginate 5 blogs %}
        <!-- <ul class="list-unstyled the-loop"> -->
        {% for blog in blogs %}

            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 blog-post-item{% if forloop.first and not category and not tag %} first-reset{% endif %}">
                {% include 'blog/blog_post.html' with include_context="index_page" %}
            </div>

        {% endfor %}
        <!-- </ul> -->

        <!-- Pagination -->
        <ul class="pagination justify-content-center mb-4">
          {% show_pages %}
        </ul>

    {% else %}
        <p>There are currently no blog posts</p>
    {% endif %}

    </div>
</div>
{% endblock %}

ndmastories/templates/blog/blog_page.html
{% extends "base.html" %}
{% load wagtailcore_tags %}


{% block content %}
    {% include 'blog/blog_post.html' with blog=self %}
    {% if COMMENTS_APP == 'django_comments_xtd' %}
        {% include 'blog/blog_post_comments_xtd.html' with blog=self %}
    {% endif %}
{% endblock %}

ndmastories/templates/blog/blog_post.html
{% load wagtailcore_tags static wagtailimages_tags blogapp_tags el_pagination_tags %}

{% if include_context == "index_page" %}

    <div class="card-body">
        {% if blog.header_image %}
            {% image blog.header_image original as header_image %}
            <a href="{% pageurl blog %}">
                <img src="{{ header_image.url }}" class="card-img-top" ></img>
            </a>
        {% endif %}

        <h2 class="card-title">
            <a href="{% pageurl blog %}">{{ blog.title }}</a>
        </h2>
        <div class="text-muted right">
            Posted on {{ blog.date }}
        </div>
        <p class="card-text">
            {% if blog.excerpt %}
            {{ blog.excerpt|richtext }}
            {% else %}
            {{ blog.body|richtext|truncatewords_html:50 }}
            {% endif %}
        </p>
        <p class="right">
            {% if blog.categories.first.category.name == 'Alerts' %}
                <a href="{% pageurl blog %}" class="downlink btn btn-primary"
                    style="float:left;">Download</a>
            {% endif %}
            <a href="{% pageurl blog %}" class="btn btn-secondary">Read More &rarr;</a>
        </p>

    <div class="share">
        <span class="st_linkedin_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="LinkedIn"></span>
        <span class="st_twitter_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="Tweet"></span>
        <span class="st_facebook_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="Facebook"></span>
        <span class="st_plusone_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="Google +1"></span>
        <span class="st_email_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="Email"></span>
        <span class="st_sharethis_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="ShareThis"></span>
    </div>

    <div class="meta card-footer text-muted">
        <div class="tags">
            {% if blog.tags.all %}
                Tags:
                    {% for tag in blog.tags.all %}
                        <a href="{% url 'blog:tag' tag.slug %}">{{ tag }}</a>{% if not forloop.last %}, {% endif %}
                    {% endfor %}
            {% endif %}
        </div>
        <div class="tags-and-comments">
            {% if blog.categories.all %}
                Posted in
                    {% for cat in blog.categories.all %}
                        <a href="{% url 'blog:category' cat.category.slug %}">{{ cat.category.name }}</a>{% if not forloop.last %}, {% endif %}
                    {% endfor %} |
            {% endif %}

            <div id="comments" class="comments">
            {% if COMMENTS_APP == 'django_comments_xtd' %}
                {% include 'blog/blog_post_comments_xtd_link.html' with blog=blog %}
            {% elif False %}
                <a href="{% pageurl blog %}#disqus_thread">No Comments</a>
            {% endif %}
            </div>
        </div>
    </div>
</div>



{% else %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="date text-muted" style="text-align:right; margin:1em 0 0;">
                    Posted on {{ blog.date }}
                </div>
                <div class="post-image" style="margin: 2em 0 0em;">
                    {% if blog.header_image %}
                        {% image blog.header_image original as header_image %}
                        <a href="{% pageurl blog %}">
                            <img src="{{ header_image.url }}" class="card-img-top" style="width: 100%;"></img>
                        </a>
                    {% endif %}
                </div>
                <div class="title" style="">
                    <h2 class="">
                        {{ blog.title }}
                    </h2>
                </div>
                <div class="post-body">
                        {{ blog.body|richtext }}
                </div>
                <p style="text-align:right;"><a href="{{ blog.get_parent.url }}" class="btn btn-primary right" >Return to blog</a></p>



                <div class="share">
                    <span class="st_linkedin_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="LinkedIn"></span>
                    <span class="st_twitter_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="Tweet"></span>
                    <span class="st_facebook_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="Facebook"></span>
                    <span class="st_plusone_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="Google +1"></span>
                    <span class="st_email_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="Email"></span>
                    <span class="st_sharethis_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="ShareThis"></span>
                </div>

                <div class="meta text-muted">
                    <div class="tags">
                        {% if blog.tags.all %}
                            Tags:
                                {% for tag in blog.tags.all %}
                                    <a href="{% url 'blog:tag' tag.slug %}">{{ tag }}</a>{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                        {% endif %}
                    </div>
                    <div class="tags-and-comments">
                        {% if blog.categories.all %}
                            Posted in
                                {% for cat in blog.categories.all %}
                                    <a href="{% url 'blog:category' cat.category.slug %}">{{ cat.category.name }}</a>{% if not forloop.last %}, {% endif %}
                                {% endfor %} |
                        {% endif %}

                        <div id="comments" class="comments">
                        {% if COMMENTS_APP == 'django_comments_xtd' %}
                            {% include 'blog/blog_post_comments_xtd_link.html' with blog=blog %}
                        {% elif False %}
                            <a href="{% pageurl blog %}#disqus_thread">No Comments</a>
                        {% endif %}
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

{% endif %}

<!--
<a class="blog-post-link" href="{% pageurl blog %}">
    <h2>{{ blog.title }}</h2>
</a>

{% if blog.date %}
    <div class="meta date">
        {{ blog.date|date:"F jS, Y" }}
        {{ blog.author }}
    </div>
{% endif %}

{% if include_context == "index_page" %}
<div class="blog-intro">
    {{ blog.body|richtext|truncatewords_html:70 }}
    <a href="{% pageurl blog %}">Read the rest of this entry &raquo;</a>
</div>
{% else %}
<div class="blog-body">
    {{ blog.body|richtext }}
</div>
{% endif %}

<div class="share">
    <span class="st_linkedin_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="LinkedIn"></span>
    <span class="st_twitter_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="Tweet"></span>
    <span class="st_facebook_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="Facebook"></span>
    <span class="st_plusone_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="Google +1"></span>
    <span class="st_email_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="Email"></span>
    <span class="st_sharethis_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="ShareThis"></span>
</div>

<div class="meta">
    <div class="tags">
        {% if blog.tags.all %}
            Tags:
                {% for tag in blog.tags.all %}
                    <a href="{% url 'blog:tag' tag.slug %}">{{ tag }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
        {% endif %}
    </div>
    <div class="tags-and-comments">
        {% if blog.categories.all %}
            Posted in
                {% for cat in blog.categories.all %}
                    <a href="{% url 'blog:category' cat.category.slug %}">{{ cat.category.name }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %} |
        {% endif %}

        <div id="comments" class="comments">
        {% if COMMENTS_APP == 'django_comments_xtd' %}
            {% include 'blog/blog_post_comments_xtd_link.html' with blog=blog %}
        {% elif False %}
            <a href="{% pageurl blog %}#disqus_thread">No Comments</a>
        {% endif %}
        </div>
    </div>
</div> -->

ndmastories/templates/blog/blog_post_comments_xtd.html
{% load comments %}

{% render_comment_list for self %}
{% render_comment_form for self %}

ndmastories/templates/blog/blog_post_comments_xtd_link.html
{% load wagtailcore_tags comments %}

{% get_comment_count for blog as comment_count %}
<p>
    <a href="{% pageurl blog %}#comments">
        {{ comment_count }} comment{{ comment_count|pluralize }}
    </a>
    {{ comment_count|pluralize:"has,have" }} been posted.
</p>